### ISSUE TITLE
Function with text default argument chokes graphiql

### ISSUE THREAD

**Issue by dvv** [supabase/pg_graphql#456]
**Describe the bug**
Not able to introspect schema when a function with a default textual argument exposed.

**To Reproduce**

Vanilla GraphiQL page served via nginx:
```html
<html>
  <head>
    <title>GraphiQL - pg_graphql</title>
    <link href="https://unpkg.com/graphiql/graphiql.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/@graphiql/plugin-explorer/dist/style.css" rel="stylesheet" />
  </head>
  <body style="margin: 0;">
    <div id="graphiql" style="height: 100vh;"></div>

    <script
      crossorigin
      src="https://unpkg.com/react/umd/react.production.min.js"
    ></script>
    <script
      crossorigin
      src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
    ></script>
    <script crossorigin src="https://unpkg.com/graphiql/graphiql.min.js"></script>
    <script crossorigin src="https://unpkg.com/@graphiql/plugin-explorer/dist/index.umd.js"></script>
    <script>
      const fetcher = GraphiQL.createFetcher({
        url: '/graphql'
      });
      const explorerPlugin = GraphiQLPluginExplorer.explorerPlugin();
      ReactDOM.render(
        React.createElement(GraphiQL, {
          fetcher,
          defaultEditorToolsVisibility: true,
          plugins: [explorerPlugin],
        }),
        document.getElementById('graphiql')
      );
    </script>
  </body>
</html>
```

Good:
```sql
drop function if exists api.foo();
create or replace function api.foo(def int = 123) returns int stable return def;
grant execute on function api.foo(int) to public;
```

Bad:
```sql
drop function if exists api.foo2();
create or replace function api.foo2(def text = '123') returns text stable return def;
grant execute on function api.foo2(text) to public;
```

GraphiQL error:
```json
{
  "errors": [
    {
      "message": "Syntax Error: Unexpected single quote character ('), did you mean to use a double quote (\")?",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ],
      "extensions": {},
      "stack": "GraphQLError: Syntax Error: Unexpected single quote character ('), did you mean to use a double quote (\")?\n    at syntaxError (https://unpkg.com/graphiql/graphiql.min.js:21716:10)\n    at readNextToken (https://unpkg.com/graphiql/graphiql.min.js:26439:40)\n    at Lexer.lookahead (https://unpkg.com/graphiql/graphiql.min.js:26224:29)\n    at Lexer.advance (https://unpkg.com/graphiql/graphiql.min.js:26208:37)\n    at Parser.expectToken (https://unpkg.com/graphiql/graphiql.min.js:28127:19)\n    at parseValue (https://unpkg.com/graphiql/graphiql.min.js:26965:10)\n    at buildInputValue (https://unpkg.com/graphiql/graphiql.min.js:33386:128)\n    at keyValMap (https://unpkg.com/graphiql/graphiql.min.js:24982:27)\n    at buildInputValueDefMap (https://unpkg.com/graphiql/graphiql.min.js:33378:37)\n    at buildField (https://unpkg.com/graphiql/graphiql.min.js:33374:13)"
    }
  ]
}
```

Traces led to `'def'` being the cause of ^^^.

**Expected behavior**
Functions with a default textual argument to not cause introspection errors.

**Versions:**
 - PostgreSQL: 16.1
 - pg_graphql commit ref: ee8ef6

**Comment by dvv** [comment]
I changed the https://github.com/supabase/pg_graphql/blob/master/src/graphql.rs#L1347 to read
```rust
default_value: format!("\"{}\"", arg_default.as_deref().unwrap_or_default()).into()
```
to temporary solve the issue.
As I'm complete 0 in Rust please consider elaborating on that.
TIA
